apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false

  - name: ExampleDB
    type: postgres
    url: '${POSTGRES_HOST}:${POSTGRES_PORT}'
    user: '${POSTGRES_USERNAME}'
    secureJsonData:
      password: '${POSTGRES_PASSWORD}'
    jsonData:
      database: example
      sslmode: 'disable' # disable/require/verify-ca/verify-full
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1700 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false