# See https://opentelemetry.io/docs/collector/configuration/
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318
  kafkametrics:
    protocol_version: 2.0.0
    brokers: kafka:29092
    scrapers:
      - brokers
      - topics
      - consumers
    collection_interval: 10s
  redis:
    endpoint: "valkey:6379"
    password: ""
    collection_interval: 10s

exporters:
  debug:
    # https://opentelemetry.io/docs/collector/internal-telemetry/
    verbosity: basic

  # Pull data
  prometheus:
    endpoint: 0.0.0.0:8889

  # # Push data
  # prometheusremotewrite:
  #   endpoint: "http://prometheus:9090/api/v1/write"
  #   tls:
  #     insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp, kafkametrics, redis]
      exporters: [debug, prometheus]
    logs:
      receivers: [otlp]
      exporters: [debug]
