{
 "title": "Kafka",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Kafka Topic Partitions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(kafka_consumer_group_lag_ratio) by (topic, partition)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum (kafka_partition_current_offset_ratio) by (topic, partition)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}