{
 "title": "Valkey",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connected Clients",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "redis_clients_connected", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Keys",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "redis_db_keys", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Commands (per second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    { "expr": "redis_commands_per_second", "legendFormat": "__auto" }
   ]
  }
 ]
}